---
- hosts: all
  user: ansadm
  become: yes
  become_method: sudo
  tasks:
    - name: Install list of packages
      yum: "name={{item}} state=present"
      with_items:
        - wget
        - vim
        - screen
        - nmap
      register: yum_result
    - name: Restart Service
      service: "name=puppet state=restarted"
      when: yum_result is changed
#
